### ISSUE TITLE
2.3.0 initialization example

### ISSUE THREAD

**Issue by JensRantil** [organicveggie/metrics-statsd#10]
Is there any example somewhere on how this reporter can be enabled/initialized for 2.3.0?

**Comment by gitlakerzhou** [comment]
I managed to make use of 2.3.0 because 3.0 seems not available. But 2.3.0 is not working properly for me. Only some metrics are sent to statsD daemon, most of metrics are lost. It seems to be a known issue for 2.3.0. 
...
            statsdReporter = Some(new StatsdReporter(host, port))
            val interval = config.getDuration(propName + "reporters.statsd.interval", TimeUnit.MILLISECONDS)
            statsdReporter.get.start(interval, TimeUnit.MILLISECONDS)
...

**Comment by JensRantil** [comment]
Thanks for an example!

> It seems to be a known issue for 2.3.0.

@gitlakerzhou Do you have any reference to this issue?

**Comment by JensRantil** [comment]
> Do you have any reference to this issue?

Answering my own question: #7.
